# ЛР2. Вероятностные конечные автоматы
## 7 вариант

### Задание:

Изучить работу вероятностного конечного автомата на примере неоднородной марковской цепи. \
-- переходные матрицы P^[t-1,t] для моментов времени t=1,..,10; \
-- нормированные переходные матрицы P^[t-1,t] для моментов времени t=1,..,10;\
-- распределение вероятностей в моменты времени t=1,..,10.

In [1]:
# подключение библиотек
import pandas as pd
import numpy as np
import itertools
import random
import math

In [63]:
# функция для расчёта вероятностей переходной матрицы на соответствующем шаге 
# рассчёт тригонометрических функций производится в радианах! 
def transition_matrix(t): 
    P = []    
    P.append( [1+math.cos(t)**2, 1+math.cos(2*t), math.cos(2*t), math.cos(t)**2] )    
    P.append( [math.sin(t)**2, math.tan(t)**2, 2*math.sin(t/2)**2, math.cos(2*t)] )  
    P.append( [t**2, 1+t**2, (1+t)**2, t+t**2] )
    P.append( [math.sqrt(abs(8-3*t)), math.sqrt(abs(8-2*t)), math.sqrt(t**2-1), 2*t] )
    P = (np.array(P)).round(5)
    
    return P

In [64]:
# начальное распределение вероятностей состояний вероятностного конечного автомата
P_ksi = np.array([0.1, 0.2, 0.3, 0.4])
P_ksi

array([0.1, 0.2, 0.3, 0.4])

In [65]:
P_t = P_ksi
print("Начальное распределение вероятностей:\nP_0 =", P_t)

for t in range(1, 11):
    P_t = (np.dot(P_t, transition_matrix(t))).round(5)
    print("\nПереходная матрица в момент времени t=%i:\n" % t)
    print(transition_matrix(t))
    print("\n\n\nРаспределение вероятности в момент времени t=%i" % t) 
    print("P_%i =" % t, P_t)

Начальное распределение вероятностей:
P_0 = [0.1 0.2 0.3 0.4]

Переходная матрица в момент времени t=1:

[[ 1.29193  0.58385 -0.41615  0.29193]
 [ 0.70807  2.42552  0.4597  -0.41615]
 [ 1.       2.       4.       2.     ]
 [ 2.23607  2.44949  0.       2.     ]]



Распределение вероятности в момент времени t=1
P_1 = [1.46523 2.12328 1.25032 1.34596]

Переходная матрица в момент времени t=2:

[[ 1.17318  0.34636 -0.65364  0.17318]
 [ 0.82682  4.7744   1.41615 -0.65364]
 [ 4.       5.       9.       6.     ]
 [ 1.41421  2.       1.73205  4.     ]]



Распределение вероятности в момент времени t=2
P_2 = [10.3793  19.58841 15.6333  11.75165]

Переходная матрица в момент времени t=3:

[[ 1.98009  1.96017  0.96017  0.98009]
 [ 0.01991  0.02032  1.98999  0.96017]
 [ 9.      10.      16.      12.     ]
 [ 1.       1.41421  2.82843  6.     ]]



Распределение вероятности в момент времени t=3
P_3 = [173.3933  193.69553 332.31815 287.09035]

Переходная матрица в момент времени t=4:

[[ 1.42725  0