# ЛР2. Вероятностные конечные автоматы
## 7 вариант

### Задание:

Изучить работу вероятностного конечного автомата на примере неоднородной марковской цепи. \
-- переходные матрицы P^[t-1,t] для моментов времени t=1,..,10; \
-- нормированные переходные матрицы P^[t-1,t] для моментов времени t=1,..,10;\
-- распределение вероятностей в моменты времени t=1,..,10.

In [1]:
# подключение библиотек
import pandas as pd
import numpy as np
import itertools
import random
import math

In [53]:
# функция для расчёта вероятностей переходной матрицы на соответствующем шаге 
# рассчёт тригонометрических функций производится в радианах! 
def transition_matrix(t): 
    P = []    
    P.append( [1+math.cos(t)**2, 1+math.cos(2*t), math.cos(2*t), math.cos(t)**2] )    
    P.append( [math.sin(t)**2, math.tan(t)**2, 2*math.sin(t/2)**2, math.cos(2*t)] )  
    P.append( [t**2, 1+t**2, (1+t)**2, t+t**2] )
    P.append( [math.sqrt(abs(8-3*t)), math.sqrt(abs(8-2*t)), math.sqrt(t**2-1), 2*t] )
    P = (np.array(P)).round(5)
    
    return P

In [60]:
# нормализация матрицы
def norm_matrix(P):
    P = abs(P)
    for i in range(P.shape[0]):
        P[i] /= sum(abs(P[i]))
    return P

In [61]:
# начальное распределение вероятностей состояний вероятностного конечного автомата
P_ksi = np.array([0.1, 0.2, 0.3, 0.4])
P_ksi

array([0.1, 0.2, 0.3, 0.4])

In [62]:
P_t = P_ksi
print("Начальное распределение вероятностей:\nP_0 =", P_t)

for t in range(1, 11):
    P_t = (np.dot(P_t, norm_matrix( transition_matrix(t)))).round(5)
    print("\nПереходная матрица в момент времени t=%i:\n" % t)
    print(norm_matrix( transition_matrix(t)))
    print("\n\n\nРаспределение вероятности в момент времени t=%i" % t) 
    print("P_%i =" % t, P_t)

Начальное распределение вероятностей:
P_0 = [0.1 0.2 0.3 0.4]

Переходная матрица в момент времени t=1:

[[0.5        0.22596038 0.16105749 0.11298213]
 [0.17660072 0.60495231 0.11465442 0.10379255]
 [0.11111111 0.22222222 0.44444444 0.22222222]
 [0.33446263 0.36638516 0.         0.2991522 ]]



Распределение вероятности в момент времени t=1
P_1 = [0.25244 0.35681 0.17237 0.21838]

Переходная матрица в момент времени t=2:

[[0.5        0.14761588 0.27857618 0.07380794]
 [0.10778502 0.62239523 0.18461063 0.08520912]
 [0.16666667 0.20833333 0.375      0.25      ]
 [0.15462167 0.21866861 0.18937249 0.43733723]]



Распределение вероятности в момент времени t=2
P_2 = [0.22717 0.343   0.24219 0.18763]

Переходная матрица в момент времени t=3:

[[0.33672022 0.33333277 0.16327978 0.16666723]
 [0.00665799 0.0067951  0.6654617  0.32108521]
 [0.19148936 0.21276596 0.34042553 0.25531915]
 [0.08894708 0.12578985 0.25158059 0.53368248]]



Распределение вероятности в момент времени t=3
P_3 = [0.141